name: flutter_complete_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  #State management.
  flutter_bloc: ^8.1.4
  #Code generation for immutable classes that has a simple syntax/API without compromising on the features.
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  #Dependency Injection.
  get_it: ^7.6.7
  #Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.3.3
  #Networking.
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  retrofit_generator: ^8.0.4
  #localization.
  intl: ^0.18.0
  easy_localization: ^3.0.0
  #splash
  flutter_native_splash: ^2.3.10
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
  firebase_core: ^2.12.0
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svgs/
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
